### ISSUE TITLE
Make available back issues/archives

### ISSUE THREAD

**Issue by felicianotech** [davidsneighbour/hugonewsletter.com#23]

**Comment by davidsneighbour** [comment]
Future issues will be part of the website in HTML format. 
Issues from v1 of the Hugo Newsletter will be made available as PDF on a subpage of the website.

**Comment by davidsneighbour** [comment]
done in b8801f08d6dd134afa5c334714ee86a0a4f5475a

navigation on website to follow ;)

http://localhost:1313/v1/
