### ISSUE TITLE
Make newsletters more mobile friendly

### ISSUE THREAD

**Issue by jcurreee** [davidsneighbour/hugonewsletter.com#24]
Small visual nit: In the message body, it might be better to move the issue (or edition, or whatever #5 results in 😃) to a new line instead of having it on a single line with the name. This would make things just a little bit cleaner in narrow views, like in mobile mail apps:

![hugo-newsletter-gmail-mobile](https://user-images.githubusercontent.com/9578797/47932941-46d7ba00-de90-11e8-8dc0-0ec8d80e3b06.jpg)

**Comment by felicianotech** [comment]
Thank you for the report.

**Comment by davidsneighbour** [comment]
The next newsletter will receive a new design/template which is mobile-first using [MJML](https://github.com/mjmlio/mjml) as engine. These issues should not come up again then. As this is a completely new template I will close this issue for now.
